services:

  # MySQL database service
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${IRIS_ROOT_PASSWORD}
      MYSQL_DATABASE: ${IRIS_SYSTEMS_REC_TASK_DATABASE_NAME}
      MYSQL_USER: ${IRIS_SYSTEMS_REC_TASK_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${IRIS_SYSTEMS_REC_TASK_DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - application
      - storage
      - monitoring
    # Healthcheck to ensure MySQL is ready before dependent services start
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  # NFS server for shared storage
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    privileged: true
    restart: unless-stopped
    environment:
      SHARED_DIRECTORY: /exports
    volumes:
      - shared_data:/exports
    networks:
      - storage

  # Application service
  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      IRIS_SYSTEMS_REC_TASK_DATABASE_USERNAME: ${IRIS_SYSTEMS_REC_TASK_DATABASE_USERNAME}
      IRIS_SYSTEMS_REC_TASK_DATABASE_PASSWORD: ${IRIS_SYSTEMS_REC_TASK_DATABASE_PASSWORD}
      IRIS_SYSTEMS_REC_TASK_DATABASE_NAME: ${IRIS_SYSTEMS_REC_TASK_DATABASE_NAME}
      IRIS_SYSTEMS_REC_TASK_DATABASE_HOST: ${IRIS_SYSTEMS_REC_TASK_DATABASE_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    networks:
      - application
      - storage
    restart: unless-stopped
    volumes:
      - type: volume
        source: shared_data
        target: /app/storage

  # Database migrator service so that we can run migrations before the app starts and ensure the database is ready before the app starts. 
  # And also to avoid running migrations every time the app container restarts/starts.
  migrator:
    build: .
    image: iris-rails-migrator
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      IRIS_SYSTEMS_REC_TASK_DATABASE_USERNAME: ${IRIS_SYSTEMS_REC_TASK_DATABASE_USERNAME}
      IRIS_SYSTEMS_REC_TASK_DATABASE_PASSWORD: ${IRIS_SYSTEMS_REC_TASK_DATABASE_PASSWORD}
      IRIS_SYSTEMS_REC_TASK_DATABASE_NAME: ${IRIS_SYSTEMS_REC_TASK_DATABASE_NAME}
      IRIS_SYSTEMS_REC_TASK_DATABASE_HOST: ${IRIS_SYSTEMS_REC_TASK_DATABASE_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: bash -c "sleep 10 && bundle exec rails db:create && bundle exec rails db:migrate"
    networks:
      - storage
      - application

  # Nginx service to serve the app and other services(like prometheus and grafana)
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # For basic authentication for prometheus and grafana
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro 
    networks:
      - public
      - application
      - monitoring

  # Monitoring services
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

  # Prometheus service to scrape metrics from various services
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring

  # cadvisor to scrape container metrics and provide them to prometheus
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/machine-id:/etc/machine-id:ro
    networks:
      - monitoring

  # MySQL exporter to scrape MySQL metrics and provide them to prometheus
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    volumes:
    # MySQL configuration files for the exporter to connect to MySQL and scrape metrics
      - ./mysqld_exporter.cnf:/etc/.mysqld_exporter.cnf:ro 
    command:
      - "--config.my-cnf=/etc/.mysqld_exporter.cnf"
    depends_on:
      - mysql
    networks:
      - monitoring

  # Node exporter to scrape host metrics and provide them to prometheus
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  mysql_data:
  grafana-data:
  shared_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs-server,rw,nolock,soft
      device: ":/exports"

networks:
  public:
  application:
  monitoring:
  storage: